build_cfg() {
    CFG="#!/bin/sh\n"
    CFG+="export V_SYS_HD=\"${install_gui_drive}\"\n"
    CFG+="export V_BOOT_SIZE=\"${install_gui_bootpar}\"\n"
    CFG+="export V_SWAP_SIZE=\"${install_gui_swappar}\"\n"
    CFG+="export V_COUNTRY=\"${install_gui_mirrorlist}\"\n"
    CFG+="export V_TIMEZONE=\"${install_gui_timezone}\"\n"
    CFG+="export V_LANGUAGE=\"${install_gui_language}\"\n"
    CFG+="export V_KEYMAP=\"${install_gui_keymap}\"\n"
    CFG+="export V_HOSTNAME=\"${install_gui_hostname}\"\n"
    CFG+="export V_ROOT_PWD=\"${install_gui_rootpwd}\"\n"
    CFG+="export V_USER_NAME=\"${install_gui_user}\"\n"
    CFG+="export V_USER_PASS=\"${install_gui_pass}\"\n"
    CFG+="export V_GUI_SEL=\"${install_gui_ui}\"\n"
    CFG+="export V_EXTRA_PKG=\"$(echo ${install_gui_extrapkg[@]})\"\n"
    CFG+="export V_AUR_PKG=(\"$(echo ${install_gui_aurpkg[@]})\")\n"
    CFG+="export V_CPU_TYPE=\"${install_gui_cpu}\"\n"
    CFG+="export V_GPU_SEL=\"${install_gui_gpu}\"\n"
    CFG+="export V_SERVICES_MY=(\"$(echo ${install_gui_services})\")\n"
    CFG+="export V_CACHYOS_REPO=\"${install_gui_cachyos_enable}\"\n"
    echo -e "${CFG}" > archinstall_setup_cfg.sh
}